theme: jekyll-theme-minimal
title: Miguel Fuertes
description: Interesting Projects!
logo: assets/portfolio.png
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]

# To further modify: https://github.com/pages-themes/minimal


#remote_theme: thelehhman/plainwhite-jekyll
#plainwhite:
#  name: Miguel Fuertes
#  tagline: Developer. Designer
#  date_format: "%b %-d, %Y"
#  social_links:
#    twitter: hkfuertes
#    github:  hkfuertes
#    linkedIn: in/hkfuertes # format: locale/username
