theme: jekyll-theme-minimal
  title: Miguel Fuertes
  description: Interesting Projects!
  logo: https://raw.githubusercontent.com/hkfuertes/hkfuertes.github.io/master/circle-cropped.png
  show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
