theme: jekyll-theme-minimal
title: Miguel Fuertes
description: Interesting Projects!
logo: https://avatars2.githubusercontent.com/u/7235263?s=460&v=4
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
