version: '3'

services:
  node:
    image: node:lts
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "4321:4321"
  # nginx:
  #   image: nginx
  #   restart: unless-stopped
  #   volumes:
  #     - ./dist:/usr/share/nginx/html
  #   ports:
  #     - "7777:80"
